services:
  hirex-postgres:
    image: postgres:15.6-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=hirex
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
