version: '3.8'

services:
#  hirex-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - hirex-postgres
#    ports:
#      - 8080:8080
#    environment:
#      - DATASOURCE_URL=jdbc:postgresql://hirex-postgres:5432/hirex
#      - DATASOURCE_USERNAME=postgres
#      - DATASOURCE_PASSWORD=123

  hirex-postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=hirex
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: